language: python
python:
  - 2.6
  - 2.7
  - 3.3
script: make test

install:
    - pip install --use-mirrors \
          `python -c 'from setup import META; print(" ".join(META["extras_require"]["testing"]))'`
